<?php
include('../db_conn.php');
include('getallInfoFolder.php');
if(isset($_POST["operacao2"]))
{
	if($_POST["operacao2"] == "Add")
	{
		$statement = $connection->prepare(
			"INSERT INTO info_folder( F_Poids, F_Taille, F_IMC, F_Bareme, F_Serol_HIV, F_Serol_HB, F_Serol_HC,
			F_Serol_CT, F_Serol_TPHA, F_Serol_VDRL, 
			F_GrpSang, F_Tabagisme, F_Alcoolisme, F_Mariage_precedent, F_Nbr_enfant, F_Type_infertilite, F_Duree_infertilite,
			F_Gestite, F_Parite, F_Naissance_vivante, F_FC, F_AntePMA_IAC, F_AntePMA_FIV, F_AntChirurgie, F_TraitMedic,
			F_J, F_AMH, F_TSH, F_FSH, F_Oestradiol, F_PRL, F_LH, F_Progesterome,
			F_SOPK, F_IO_, F_IOP, F_Endometriose, 
			F_Hysterosalpingographie, F_Polypes_fibromes, F_CFA_Droit, F_CFA_Gauche, F_Commentaire, ID_Patientfk,

			H_poids, H_taille, H_IMC, H_bareme, H_HIV, H_HB, H_HC, H_CT, H_TPHA, H_VDRL,
			H_Diabete, H_TABAGISM, H_ALCOOLISME, H_MARIAGE, H_NbrEnfant, H_TpInfer, H_DureeInfer, H_AntChirurgie,
			H_TraitMedic, H_FSH, H_Testosterone, H_PRL, H_Date, H_Abstinence, H_Volume, H_Concentration,
			H_FormeTypique, H_MobiliteTotal, H_Mobilite, H_Conclusion, H_Varicocele, H_Cryptorchidie, 
			H_asectomie, H_TorisonTesticulaire, H_EjaculationRetrograde, H_AtrophieTesticulaire, H_DysfonctionErectile,
			H_TestFragmentationADN, H_MicrodeletionChromosomeY, H_SyndromeKinefelter, H_Caryotype, H_MarTest, H_Commentaire,
			
			medecinTraitant, dateDebut, dureeStimuOvarienne, traitementDoseTotale,
			spermeFrais, spermeCongele, biopsieTesticulaire,
			delaiDabstinence, mobiliteTotale, volume, concentration, mobiliteProgressive, formesTypiques,
			datePonstionFolliculaire,
			nbOvocytesRecup, nbOvocytesMatures, nbOvocytesFecondes,
			nbEmbryonsObtenus, nbEmbryonsCultureProlongee, nbBlastocystesObtenus,
			nbEmbryonsVitrifies, nbEmbryonsTransferes, nbBlastocystesVitrifies,
			nbTotalPaillettes, dateVitrification, nbEmbryonsBlastocytesVitrifies, dateRenouvellement, 
			QualiteEmbryonnaire0, QualiteEmbryonnaire1, QualiteEmbryonnaire2, QualiteEmbryonnaire3, QualiteEmbryonnaire4,
			QualiteEmbryonnaire5, QualiteEmbryonnaire6, QualiteEmbryonnaire7, QualiteEmbryonnaire8, QualiteEmbryonnaire9,
			dateDevitrificationTEC, nbPailletteDevitrifieeTEC, nbEmbryonsBlastocytesDevitrifiesTEC, resteTEC, dateRenouvellementTEC)

			VALUES (:fpoids, :ftaille, :fIMC, :fbareme, :fHIV, :fHB, :fHC, :fCT, :fTPHA, :fVDRL,
			:fGrpSanguine, :fTABAGISM, :fALCOOLISME, :fMARIAGE, :fNbrEnfant, :fTpInfer, :fDureeInfer,
			:fGESTITE, :fPARITE, :fNaissaceVivante, :fFC, :fAntecedentPMA_IAC, :fAntecedentPMA_FIV, :fAntChirurgie, :fTraitMedic,
			:fJ, :fAMH, :fTSH, :fFSH, :fOEstradiol, :fPRL, :fLH, :fProgesterone,
			:fSOPK, :fIO, :fIOP, :fEndometriose,
			:fHysterosalpingographie, :fPolypesFibromes, :fCFA_Droit, :fCFA_Gauche, :fCommentaire, :patient_idfk, 
		
			:hpoids, :htaille, :hIMC, :hbareme, :hHIV, :hHB, :hHC, :hCT, :hTPHA, :hVDRL,
			:hDiabete, :hTABAGISM, :hALCOOLISME, :hMARIAGE, :hNbrEnfant, :hTpInfer, :hDureeInfer, :hAntChirurgie,
			:hTraitMedic, :hFSH, :hTestosterone, :hPRL, :hDate, :hAbstinence, :hVolume, :hConcentration,
			:hFormeTypique, :hMobiliteTotal, :hMobilite, :hConclusion, :hVaricocele, :hCryptorchidie,
			:hVasectomie, :hTorisonTesticulaire, :hEjaculationRetrograde, :hAtrophieTesticulaire, :hDysfonctionErectile,
			:hTestFragmentationADN, :hMicrodeletionChromosomeY, :hSyndromeKinefelter, :hCaryotype, :hMarTest, :hCommentaire,
			
			:medecinTraitant, :dateDebut, :dureeStimuOvarienne, :traitementDoseTotale,
			:spermeFrais, :spermeCongele, :biopsieTesticulaire,
			:delaiDabstinence, :mobiliteTotale, :volume, :concentration, :mobiliteProgressive, :formesTypiques,
			:datePonstionFolliculaire,
			:nbOvocytesRecup, :nbOvocytesMatures, :nbOvocytesFecondes,
			:nbEmbryonsObtenus, :nbEmbryonsCultureProlongee, :nbBlastocystesObtenus,
			:nbEmbryonsVitrifies, :nbEmbryonsTransferes, :nbBlastocystesVitrifies,
			:nbTotalPaillettes, :dateVitrification, :nbEmbryonsBlastocytesVitrifies, :dateRenouvellement,
			:QualiteEmbryonnaire0, :QualiteEmbryonnaire1, :QualiteEmbryonnaire2, :QualiteEmbryonnaire3, :QualiteEmbryonnaire4,
			:QualiteEmbryonnaire5, :QualiteEmbryonnaire6, :QualiteEmbryonnaire7, :QualiteEmbryonnaire8, :QualiteEmbryonnaire9,
			:dateDevitrificationTEC, :nbPailletteDevitrifieeTEC, :nbEmbryonsBlastocytesDevitrifiesTEC, :resteTEC, :dateRenouvellementTEC)"
		);
	
			$resultado = $statement->execute(
				array(
					//---------------FEMALE---------------
					':fpoids'	=>	$_POST["fpoids"],
					':ftaille'	=>	$_POST["ftaille"],
					':fIMC'	=>	$_POST["fIMC"],
					':fbareme'	=>	$_POST["fbareme"],
					':fHIV'	=>	$_POST["fHIV"],
					':fHB'	=>	$_POST["fHB"],
					':fHC'	=>	$_POST["fHC"],
					':fCT'	=>	$_POST["fCT"],
					':fTPHA'	=>	$_POST["fTPHA"],
					':fVDRL'	=>	$_POST["fVDRL"],
					':fGrpSanguine'	=>	$_POST["fGrpSanguine"],
					':fTABAGISM'	=>	$_POST["fTABAGISM"],
					':fALCOOLISME'	=>	$_POST["fALCOOLISME"],
					':fMARIAGE'	=>	$_POST["fMARIAGE"],
					':fNbrEnfant'	=>	$_POST["fNbrEnfant"],
					':fTpInfer'	=>	$_POST["fTpInfer"],
					':fDureeInfer'	=>	$_POST["fDureeInfer"],
					':fGESTITE'	=>	$_POST["fGESTITE"],
					':fPARITE'	=>	$_POST["fPARITE"],
					':fNaissaceVivante'	=>	$_POST["fNaissaceVivante"],
					':fFC'	=>	$_POST["fFC"],
					':fAntecedentPMA_IAC'	=> isset($_POST["fAntecedentPMA_IAC"]) ? "true" : "false",
					':fAntecedentPMA_FIV'	=>	isset($_POST["fAntecedentPMA_FIV"]) ? "true" : "false",
					':fAntChirurgie'	=>	$_POST["fAntChirurgie"],
					':fTraitMedic'	=>	$_POST["fTraitMedic"],
					':fJ'	=>	$_POST["fJ"],
					':fAMH'	=>	$_POST["fAMH"],
					':fTSH'	=>	$_POST["fTSH"],
					':fFSH'	=>	$_POST["fFSH"],
					':fOEstradiol'	=>	$_POST["fOEstradiol"],
					':fPRL'	=>	$_POST["fPRL"],
					':fLH'	=>	$_POST["fLH"],
					':fProgesterone'	=>	$_POST["fProgesterone"],
					':fSOPK'	=>	isset($_POST["fSOPK"]) ? "true" : "false",
					':fIO'	=>	isset($_POST["fIO"]) ? "true" : "false",
					':fIOP'	=>	isset($_POST["fIOP"]) ? "true" : "false",
					':fEndometriose'	=>	isset($_POST["fEndometriose"]) ? "true" : "false",
					':fHysterosalpingographie'	=>	isset($_POST["fHysterosalpingographie"]) ? "true" : "false",
					':fPolypesFibromes'	=>	isset($_POST["fPolypesFibromes"]) ? "true" : "false",
					':fCFA_Droit'	=>	$_POST["fCFA_Droit"],
					':fCFA_Gauche'	=>	$_POST["fCFA_Gauche"],
					':fCommentaire'	=>	$_POST["fCommentaire"],
					':patient_idfk'	=>	$_POST["patient_idfk"],
					
					// ---------------MALE---------------
					':hpoids'	=>	$_POST["hpoids"],
					':htaille'	=>	$_POST["htaille"],
					':hIMC'	=>	$_POST["hIMC"],
					':hbareme'	=>	$_POST["hbareme"],
					':hHIV'	=>	$_POST["hHIV"],
					':hHB'	=>	$_POST["hHB"],
					':hHC'	=>	$_POST["hHC"],
					':hCT'	=>	$_POST["hCT"],
					':hTPHA'	=>	$_POST["hTPHA"],
					':hVDRL'	=>	$_POST["hVDRL"],
					':hDiabete'	=>	$_POST["hDiabete"],
					':hTABAGISM'	=>	$_POST["hTABAGISM"],
					':hALCOOLISME'	=>	$_POST["hALCOOLISME"],
					':hMARIAGE'	=>	$_POST["hMARIAGE"],
					':hNbrEnfant'	=>	$_POST["hNbrEnfant"],
					':hTpInfer'	=>	$_POST["hTpInfer"],
					':hDureeInfer'	=>	$_POST["hDureeInfer"],
					':hAntChirurgie'	=>	$_POST["hAntChirurgie"],
					':hTraitMedic'	=>	$_POST["hTraitMedic"],
					':hFSH'	=>	$_POST["hFSH"],
					':hTestosterone'	=>	$_POST["hTestosterone"],
					':hPRL'	=>	$_POST["hPRL"],
					':hDate'	=>	$_POST["hDate"],
					':hAbstinence'	=>	$_POST["hAbstinence"],
					':hVolume'	=>	$_POST["hVolume"],
					':hConcentration'	=>	$_POST["hConcentration"],
					':hFormeTypique'	=>	$_POST["hFormeTypique"],
					':hMobiliteTotal'	=>	$_POST["hMobiliteTotal"],
					':hMobilite'	=>	$_POST["hMobilite"],
					':hConclusion'	=>	$_POST["hConclusion"],
					':hTorisonTesticulaire'	=>	$_POST["hTorisonTesticulaire"],
					':hEjaculationRetrograde'	=>	$_POST["hEjaculationRetrograde"],
					':hAtrophieTesticulaire'	=>	$_POST["hAtrophieTesticulaire"],
					':hDysfonctionErectile'	=>	$_POST["hDysfonctionErectile"],
					':hVaricocele'	=>	$_POST["hVaricocele"],
					':hCryptorchidie'	=>	$_POST["hCryptorchidie"],
					':hVasectomie'	=>	$_POST["hVasectomie"],
					':hTestFragmentationADN'	=>	$_POST["hTestFragmentationADN"],
					':hMicrodeletionChromosomeY'	=>	$_POST["hMicrodeletionChromosomeY"],
					':hSyndromeKinefelter'	=>	$_POST["hSyndromeKinefelter"],
					':hCaryotype'	=>	$_POST["hCaryotype"],
					':hMarTest'	=>	$_POST["hMarTest"],
					':hCommentaire'	=>	$_POST["hCommentaire"],

					//3 FORM
					':medecinTraitant'	=>	$_POST["medecinTraitant"],
					':dateDebut'	=>	$_POST["dateDebut"],
					':dureeStimuOvarienne'	=>	$_POST["dureeStimuOvarienne"],
					':traitementDoseTotale'	=>	$_POST["traitementDoseTotale"],
					':spermeFrais'	=>	$_POST["spermeFrais"],
					':spermeCongele'	=>	$_POST["spermeCongele"],
					':biopsieTesticulaire'	=>	$_POST["biopsieTesticulaire"],
					':delaiDabstinence'	=>	$_POST["delaiDabstinence"],
					':mobiliteTotale'	=>	$_POST["mobiliteTotale"],
					':volume'	=>	$_POST["volume"],
					':concentration'	=>	$_POST["concentration"],
					':mobiliteProgressive'	=>	$_POST["mobiliteProgressive"],
					':formesTypiques'	=>	$_POST["formesTypiques"],
					':datePonstionFolliculaire'	=>	$_POST["datePonstionFolliculaire"],
					':nbOvocytesRecup'	=>	$_POST["nbOvocytesRecup"],
					':nbOvocytesMatures'	=>	$_POST["nbOvocytesMatures"],
					':nbOvocytesFecondes'	=>	$_POST["nbOvocytesFecondes"],
					':nbEmbryonsObtenus'	=>	$_POST["nbEmbryonsObtenus"],
					':nbEmbryonsCultureProlongee'	=>	$_POST["nbEmbryonsCultureProlongee"],
					':nbBlastocystesObtenus'	=>	$_POST["nbBlastocystesObtenus"],
					':nbEmbryonsVitrifies'	=>	$_POST["nbEmbryonsVitrifies"],
					':nbEmbryonsTransferes'	=>	$_POST["nbEmbryonsTransferes"],
					':nbBlastocystesVitrifies'	=>	$_POST["nbBlastocystesVitrifies"],
					':nbTotalPaillettes'	=>	$_POST["nbTotalPaillettes"],
					':dateVitrification'	=>	$_POST["dateVitrification"],
					':nbEmbryonsBlastocytesVitrifies'	=>	$_POST["nbEmbryonsBlastocytesVitrifiesText"],
					':dateRenouvellement'	=>	$_POST["dateRenouvellement"],

					':QualiteEmbryonnaire0'	=>	$_POST["QualiteEmbryonnaire0"],
					':QualiteEmbryonnaire1'	=>	$_POST["QualiteEmbryonnaire1"],
					':QualiteEmbryonnaire2'	=>	$_POST["QualiteEmbryonnaire2"],
					':QualiteEmbryonnaire3'	=>	$_POST["QualiteEmbryonnaire3"],
					':QualiteEmbryonnaire4'	=>	$_POST["QualiteEmbryonnaire4"],
					':QualiteEmbryonnaire5'	=>	$_POST["QualiteEmbryonnaire5"],
					':QualiteEmbryonnaire6'	=>	$_POST["QualiteEmbryonnaire6"],
					':QualiteEmbryonnaire7'	=>	$_POST["QualiteEmbryonnaire7"],
					':QualiteEmbryonnaire8'	=>	$_POST["QualiteEmbryonnaire8"],
					':QualiteEmbryonnaire9'	=>	$_POST["QualiteEmbryonnaire9"],

					':dateDevitrificationTEC'	=>	$_POST["dateDevitrificationTEC"],
					':nbPailletteDevitrifieeTEC'	=>	$_POST["nbPailletteDevitrifieeTEC"],
					':nbEmbryonsBlastocytesDevitrifiesTEC'	=>	$_POST["nbEmbryonsBlastocytesDevitrifiesTEC"],
					':resteTEC'	=>	$_POST["resteTEC"],
					':dateRenouvellementTEC'	=>	$_POST["dateRenouvellementTEC"],

					)
				);

		if(!empty($resultado))
		{
			echo 'Dossier créé.';
		}
	}
	
	if($_POST["operacao2"] == "Edit")
	{
		$statement = $connection->prepare(
			" UPDATE Info_Folder
			 SET F_Poids = :fpoids, F_Taille = :ftaille, F_IMC = :fIMC, F_Bareme = :fbareme, F_Serol_HIV = :fHIV, F_Serol_HB = :fHB, F_Serol_HC = :fHC, F_Serol_CT = :fCT,
				F_Serol_TPHA = :fTPHA, F_Serol_VDRL = :fVDRL, F_GrpSang = :fGrpSanguine, F_Tabagisme = :fTABAGISM, F_Alcoolisme = :fALCOOLISME, F_Mariage_precedent = :fMARIAGE,
				F_Nbr_enfant = :fNbrEnfant, F_Type_infertilite = :fTpInfer, F_Duree_infertilite = :fDureeInfer, F_Gestite = :fGESTITE, F_Parite = :fPARITE,
				F_Naissance_vivante = :fNaissaceVivante, F_FC = :fFC, F_AntePMA_IAC = :fAntecedentPMA_IAC, F_AntePMA_FIV = :fAntecedentPMA_FIV, F_AntChirurgie = :fAntChirurgie,
				F_TraitMedic = :fTraitMedic, F_J = :fJ, F_AMH = :fAMH, F_TSH = :fTSH, F_FSH = :fFSH, F_Oestradiol = :fOEstradiol, F_PRL = :fPRL, F_LH = :fLH, F_Progesterome = :fProgesterone,
				F_SOPK = :fSOPK, F_IO_ = :fIO, F_IOP = :fIOP, F_Endometriose = :fEndometriose, F_Hysterosalpingographie = :fHysterosalpingographie, F_Polypes_fibromes = :fPolypesFibromes, 
				F_CFA_Droit = :fCFA_Droit, F_CFA_Gauche = :fCFA_Gauche, F_Commentaire = :fCommentaire,

				H_poids = :hpoids, H_taille = :htaille, H_IMC = :hIMC, H_bareme = :hbareme, H_HIV = :hHIV, H_HB = :hHB, H_HC = :hHC, H_CT = :hCT, H_TPHA = :hTPHA, H_VDRL = :hVDRL,
				H_Diabete = :hDiabete, H_TABAGISM = :hTABAGISM, H_ALCOOLISME = :hALCOOLISME, H_MARIAGE = :hMARIAGE, H_NbrEnfant = :hNbrEnfant, H_TpInfer = :hTpInfer, H_DureeInfer =:hDureeInfer,
				H_AntChirurgie = :hAntChirurgie , H_TraitMedic = :hTraitMedic, H_FSH = :hFSH , H_Testosterone = :hTestosterone, H_PRL = :hPRL, H_Date = :hDate, H_Abstinence = :hAbstinence,
				H_Volume = :hVolume, H_Concentration = :hConcentration, H_FormeTypique = :hFormeTypique, H_MobiliteTotal = :hMobiliteTotal, H_Mobilite = :hMobilite, H_Conclusion = :hConclusion,
				H_Varicocele = :hVaricocele , H_Cryptorchidie = :hCryptorchidie, H_asectomie = :hVasectomie, H_TorisonTesticulaire = :hTorisonTesticulaire, H_EjaculationRetrograde = :hEjaculationRetrograde,
				H_AtrophieTesticulaire = :hAtrophieTesticulaire, H_DysfonctionErectile = :hDysfonctionErectile, H_TestFragmentationADN = :hTestFragmentationADN,
				H_MicrodeletionChromosomeY = :hMicrodeletionChromosomeY, H_SyndromeKinefelter = :hSyndromeKinefelter, H_Caryotype = :hCaryotype, H_MarTest = :hMarTest, H_Commentaire = :hCommentaire,

				medecinTraitant = :medecinTraitant, dateDebut = :dateDebut, dureeStimuOvarienne = :dureeStimuOvarienne, traitementDoseTotale = :traitementDoseTotale,
				spermeFrais = :spermeFrais, spermeCongele = :spermeCongele, biopsieTesticulaire  = :biopsieTesticulaire,
				delaiDabstinence = :delaiDabstinence, mobiliteTotale = :mobiliteTotale, volume = :volume, concentration = :concentration, mobiliteProgressive = :mobiliteProgressive, formesTypiques = :formesTypiques,
				datePonstionFolliculaire = :datePonstionFolliculaire,
				nbOvocytesRecup = :nbOvocytesRecup, nbOvocytesMatures = :nbOvocytesMatures, nbOvocytesFecondes = :nbOvocytesFecondes,
				nbEmbryonsObtenus = :nbEmbryonsObtenus, nbEmbryonsCultureProlongee = :nbEmbryonsCultureProlongee, nbBlastocystesObtenus = :nbBlastocystesObtenus,
				nbEmbryonsVitrifies = :nbEmbryonsVitrifies, nbEmbryonsTransferes = :nbEmbryonsTransferes, nbBlastocystesVitrifies = :nbBlastocystesVitrifies,
				nbTotalPaillettes = :nbTotalPaillettes, dateVitrification = :dateVitrification, nbEmbryonsBlastocytesVitrifies = :nbEmbryonsBlastocytesVitrifies, dateRenouvellement = :dateRenouvellement,
				QualiteEmbryonnaire0 = :QualiteEmbryonnaire0, QualiteEmbryonnaire1 = :QualiteEmbryonnaire1,
				QualiteEmbryonnaire2 = :QualiteEmbryonnaire2, QualiteEmbryonnaire3 = :QualiteEmbryonnaire3, 
				QualiteEmbryonnaire4 = :QualiteEmbryonnaire4, QualiteEmbryonnaire5 = :QualiteEmbryonnaire5,
				QualiteEmbryonnaire6 = :QualiteEmbryonnaire6, QualiteEmbryonnaire7 = :QualiteEmbryonnaire7,
				QualiteEmbryonnaire8 = :QualiteEmbryonnaire8, QualiteEmbryonnaire9 = :QualiteEmbryonnaire9,
				dateDevitrificationTEC = :dateDevitrificationTEC, nbPailletteDevitrifieeTEC = :nbPailletteDevitrifieeTEC,
				nbEmbryonsBlastocytesDevitrifiesTEC = :nbEmbryonsBlastocytesDevitrifiesTEC, resteTEC = :resteTEC,
				dateRenouvellementTEC = :dateRenouvellementTEC

			WHERE ID_Patientfk = :patient_idfk "
		);

		$resultado = $statement->execute(
			array(
			':fpoids'	=>	$_POST["fpoids"],
			':ftaille'	=>	$_POST["ftaille"],
			':fIMC'	=>	$_POST["fIMC"],
			':fbareme'	=>	$_POST["fbareme"],
			':fHIV'	=>	$_POST["fHIV"],
			':fHB'	=>	$_POST["fHB"],
			':fHC'	=>	$_POST["fHC"],
			':fCT'	=>	$_POST["fCT"],
			':fTPHA'	=>	$_POST["fTPHA"],
			':fVDRL'	=>	$_POST["fVDRL"],
			':fGrpSanguine'	=>	$_POST["fGrpSanguine"],
			':fTABAGISM'	=>	$_POST["fTABAGISM"],
			':fALCOOLISME'	=>	$_POST["fALCOOLISME"],
			':fMARIAGE'	=>	$_POST["fMARIAGE"],
			':fNbrEnfant'	=>	$_POST["fNbrEnfant"],
			':fTpInfer'	=>	$_POST["fTpInfer"],
			':fDureeInfer'	=>	$_POST["fDureeInfer"],
			':fGESTITE'	=>	$_POST["fGESTITE"],
			':fPARITE'	=>	$_POST["fPARITE"],
			':fNaissaceVivante'	=>	$_POST["fNaissaceVivante"],
			':fFC'	=>	$_POST["fFC"],
			':fAntecedentPMA_IAC'	=>	$_POST["fAntecedentPMA_IAC"],
			':fAntecedentPMA_FIV'	=>	$_POST["fAntecedentPMA_FIV"],
			':fAntChirurgie'	=>	$_POST["fAntChirurgie"],
			':fTraitMedic'	=>	$_POST["fTraitMedic"],
			':fJ'	=>	$_POST["fJ"],
			':fAMH'	=>	$_POST["fAMH"],
			':fTSH'	=>	$_POST["fTSH"],
			':fFSH'	=>	$_POST["fFSH"],
			':fOEstradiol'	=>	$_POST["fOEstradiol"],
			':fPRL'	=>	$_POST["fPRL"],
			':fLH'	=>	$_POST["fLH"],
			':fProgesterone'	=>	$_POST["fProgesterone"],
			':fSOPK'	=>	$_POST["fSOPK"],
			':fIO'	=>	$_POST["fIO"],
			':fIOP'	=>	$_POST["fIOP"],
			':fEndometriose'	=>	$_POST["fEndometriose"],
			':fHysterosalpingographie'	=>	$_POST["fHysterosalpingographie"],
			':fPolypesFibromes'	=>	$_POST["fPolypesFibromes"],
			':fCFA_Droit'	=>	$_POST["fCFA_Droit"],
			':fCFA_Gauche'	=>	$_POST["fCFA_Gauche"],
			':fCommentaire'	=>	$_POST["fCommentaire"],
			':patient_idfk'	=>  $_POST["patient_idfk"],
			// MALE
			':hpoids'	=>	$_POST["hpoids"],
			':htaille'	=>	$_POST["htaille"],
			':hIMC'	=>	$_POST["hIMC"],
			':hbareme'	=>	$_POST["hbareme"],
			':hHIV'	=>	$_POST["hHIV"],
			':hHB'	=>	$_POST["hHB"],
			':hHC'	=>	$_POST["hHC"],
			':hCT'	=>	$_POST["hCT"],
			':hTPHA'	=>	$_POST["hTPHA"],
			':hVDRL'	=>	$_POST["hVDRL"],
			':hDiabete'	=>	$_POST["hDiabete"],
			':hTABAGISM'	=>	$_POST["hTABAGISM"],
			':hALCOOLISME'	=>	$_POST["hALCOOLISME"],
			':hMARIAGE'	=>	$_POST["hMARIAGE"],
			':hNbrEnfant'	=>	$_POST["hNbrEnfant"],
			':hTpInfer'	=>	$_POST["hTpInfer"],
			':hDureeInfer'	=>	$_POST["hDureeInfer"],
			':hAntChirurgie'	=>	$_POST["hAntChirurgie"],
			':hTraitMedic'	=>	$_POST["hTraitMedic"],
			':hFSH' =>	$_POST["hFSH"],
			':hTestosterone'	=>	$_POST["hTestosterone"],
			':hPRL'	=>	$_POST["hPRL"],
			':hDate'	=>	$_POST["hDate"],
			':hAbstinence'	=>	$_POST["hAbstinence"],
			':hVolume'	=>	$_POST["hVolume"],
			':hConcentration'	=>	$_POST["hConcentration"],
			':hFormeTypique'	=>	$_POST["hFormeTypique"],
			':hMobiliteTotal'	=>	$_POST["hMobiliteTotal"],
			':hMobilite'	=>	$_POST["hMobilite"],
			':hConclusion'	=>	$_POST["hConclusion"],
			':hVaricocele'	=>	$_POST["hVaricocele"],
			':hTorisonTesticulaire'	=>	$_POST["hTorisonTesticulaire"],
			':hEjaculationRetrograde'	=>	$_POST["hEjaculationRetrograde"],
			':hAtrophieTesticulaire'	=>	$_POST["hAtrophieTesticulaire"],
			':hDysfonctionErectile'	=>	$_POST["hDysfonctionErectile"],
			':hCryptorchidie'	=>	$_POST["hCryptorchidie"],
			':hVasectomie'	=>	$_POST["hVasectomie"],
			':hTestFragmentationADN'	=>	$_POST["hTestFragmentationADN"],
			':hMicrodeletionChromosomeY'	=>	$_POST["hMicrodeletionChromosomeY"],
			':hSyndromeKinefelter'	=>	$_POST["hSyndromeKinefelter"],
			':hCaryotype'	=>	$_POST["hCaryotype"],
			':hMarTest'	=>	$_POST["hMarTest"],
			':hCommentaire'	=>	$_POST["hCommentaire"],
			//3 FORM
			':medecinTraitant'	=>	$_POST["medecinTraitant"],
			':dateDebut'	=>	$_POST["dateDebut"],
			':dureeStimuOvarienne'	=>	$_POST["dureeStimuOvarienne"],
			':traitementDoseTotale'	=>	$_POST["traitementDoseTotale"],
			':spermeFrais'	=>	$_POST["spermeFrais"],
			':spermeCongele'	=>	$_POST["spermeCongele"],
			':biopsieTesticulaire'	=>	$_POST["biopsieTesticulaire"],
			':delaiDabstinence'	=>	$_POST["delaiDabstinence"],
			':mobiliteTotale'	=>	$_POST["mobiliteTotale"],
			':volume'	=>	$_POST["volume"],
			':concentration'	=>	$_POST["concentration"],
			':mobiliteProgressive'	=>	$_POST["mobiliteProgressive"],
			':formesTypiques'	=>	$_POST["formesTypiques"],
			':datePonstionFolliculaire'	=>	$_POST["datePonstionFolliculaire"],
			':nbOvocytesRecup'	=>	$_POST["nbOvocytesRecup"],
			':nbOvocytesMatures'	=>	$_POST["nbOvocytesMatures"],
			':nbOvocytesFecondes'	=>	$_POST["nbOvocytesFecondes"],
			':nbEmbryonsObtenus'	=>	$_POST["nbEmbryonsObtenus"],
			':nbEmbryonsCultureProlongee'	=>	$_POST["nbEmbryonsCultureProlongee"],
			':nbBlastocystesObtenus'	=>	$_POST["nbBlastocystesObtenus"],
			':nbEmbryonsVitrifies'	=>	$_POST["nbEmbryonsVitrifies"],
			':nbEmbryonsTransferes'	=>	$_POST["nbEmbryonsTransferes"],
			':nbBlastocystesVitrifies'	=>	$_POST["nbBlastocystesVitrifies"],
			':nbTotalPaillettes'	=>	$_POST["nbTotalPaillettes"],
			':dateVitrification'	=>	$_POST["dateVitrification"],
			':nbEmbryonsBlastocytesVitrifies'	=>	$_POST["nbEmbryonsBlastocytesVitrifiesText"],
			':dateRenouvellement'	=>	$_POST["dateRenouvellement"],
			':QualiteEmbryonnaire0'	=>	$_POST["QualiteEmbryonnaire0"],
			':QualiteEmbryonnaire1'	=>	$_POST["QualiteEmbryonnaire1"],
			':QualiteEmbryonnaire2'	=>	$_POST["QualiteEmbryonnaire2"],
			':QualiteEmbryonnaire3'	=>	$_POST["QualiteEmbryonnaire3"],
			':QualiteEmbryonnaire4'	=>	$_POST["QualiteEmbryonnaire4"],
			':QualiteEmbryonnaire5'	=>	$_POST["QualiteEmbryonnaire5"],
			':QualiteEmbryonnaire6'	=>	$_POST["QualiteEmbryonnaire6"],
			':QualiteEmbryonnaire7'	=>	$_POST["QualiteEmbryonnaire7"],
			':QualiteEmbryonnaire8'	=>	$_POST["QualiteEmbryonnaire8"],
			':QualiteEmbryonnaire9'	=>	$_POST["QualiteEmbryonnaire9"],

			':dateDevitrificationTEC'	=>	$_POST["dateDevitrificationTEC"],
			':nbPailletteDevitrifieeTEC'	=>	$_POST["nbPailletteDevitrifieeTEC"],
			':nbEmbryonsBlastocytesDevitrifiesTEC'	=>	$_POST["nbEmbryonsBlastocytesDevitrifiesTEC"],
			':resteTEC'	=>	$_POST["resteTEC"],
			':dateRenouvellementTEC'	=>	$_POST["dateRenouvellementTEC"],
			
			)
		);

		if(!empty($resultado))
		{
			echo 'Dossier modifié.';
		}
	}
}
?>